Adding plon.shm and updating ntfs tools
Added plaction.shm for reference
Added plon.shm as reduced version of plaction.shm

Updated ntfs-* to use plon.shm

diff --git a/ntfs-expand b/ntfs-expand
--- a/ntfs-expand
+++ b/ntfs-expand
@@ -1,26 +1,22 @@
 #!/bin/bash
 
-set -e
-PATH="/bin:/sbin:/usr/bin:/usr/sbin"
-
-if [ -z `which ntfsresize` ]; then
-	echo "error: ntfsresize not found"
-	exit 1
+if ! source plon.shm; then
+	echo 'error: plon.shm not found in $PATH'
+	exit 255
 fi
+
+MISSING=$(plon_check_progs ntfsresize awk) \
+	|| { echo_error "error: $MISSING not found"; exit 1; }
+
+[ $# -eq 1 ] \
+	|| { echo_error "usage $PLON_0 device" ; exit 2; }
+
+[ -b "$1" ] \
+	|| { echo_error "error: $DEV is not a block device"; exit 3; }
 
 DEV="$1"
-if [ $# -ne 1 ]; then
-	echo "usage $(basename -- "$0") device"
-	exit 2
-fi
-
-if [ ! -b "$DEV" ]; then
-	echo "error: $DEV is not a block device" >&2
-	exit 3
-fi
-
 PARTSIZE=$(ntfsresize -i "$DEV" | grep '^Current device size' | awk '{print $4}')
+[ plon_is_numeric "$PARTSIZE" ] || { echo_error "error: unable to get partition size"; exit 4; }
 
-# Now expand
 ntfsresize -f -s "$PARTSIZE" "$DEV"
 
diff --git a/ntfs-reduce b/ntfs-reduce
--- a/ntfs-reduce
+++ b/ntfs-reduce
@@ -1,26 +1,20 @@
 #!/bin/bash
 
-set -e
-PATH="/bin:/sbin:/usr/bin:/usr/sbin"
-
-if [ -z `which ntfsresize` ]; then
-	echo "error: ntfsresize not found"
-	exit 1
+if ! source plon.shm 2>/dev/null; then
+	echo "error: plon.shm not found uin \$PATH"
+	exit 255
 fi
 
+MISSING=$(plon_check_progs ntfsresize grep awk)
+[ -z "$MISSING" ] || { echo_error "Missing program $MISSING";           exit 1; }
+[ $# -eq 1 ]      || { echo_error "usage $PLON_0 device" ;              exit 2; }
+[ -b "$1" ]       || { echo_error "error: $DEV is not a block device" ; exit 3; }
+
+# ntfsrezize reports MB as (bytes/1000/1000)+1
 DEV="$1"
-if [ $# -ne 1 ]; then
-	echo "usage $(basename -- "$0") device"
-	exit 2
-fi
-
-if [ ! -b "$DEV" ]; then
-	echo "error: $DEV is not a block device" >&2
-	exit 3
-fi
-
-# ntfsrezize reports MB as (bytes/1000/1000)+1, we add 10MB
-MINSIZE=$[$(ntfsresize  -i -n "$DEV" | grep 'You might resize at' | awk '{print $5}')+${MB_TO_ADD}000000]
+MB_TO_ADD="100"
+MINSIZE=$[$(LANG=C ntfsresize  -i -n "$DEV" | grep 'You might resize at' | awk '{print $5}')+${MB_TO_ADD}000000]
+[ plon_is_numeric "$MINSIZE" ] || { echo_error "error: unable to get minimun size"; exit 4; }
 
 # Now reduce
 ntfsresize -f -s $MINSIZE "$DEV"
